### ISSUE TITLE
Is license LGPLv3.0 or GPLv3.0?

### ISSUE THREAD

**Issue by Panquesito7** [poikilos/io_import_x#17]
Readme mentions it's under the GPLv3.0, but the file is the LGPLv3.0 license.

Off-topic: if it's GPLv3.0, you can probably incorporate the export option from [Minetest's X exporter](https://github.com/minetest/io_scene_x) (and make sure it works in the latest Blender versions) which is also under the same license.

**Comment by Poikilos** [comment]
As I discovered at <https://github.com/spamandeggs/directX_blender/issues/6>:

> The license is the [GNU General Public License v3](https://www.gnu.org/licenses/gpl-3.0.en.html).
> Although the original repo did not have a license file, the plugin is also at Blender's [svn](https://svn.blender.org/svnroot/bf-extensions/contrib/py/scripts/addons/io_directx_bel/) and [git](https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/refs/heads/blender2.7:/io_directx_bel) repos, and therefore under the [GPL](https://git.blender.org/gitweb/gitweb.cgi/blender.git/tree/HEAD:/doc/license) as required by Blender Foundation for all add-ons. Any public licensed code cannot later be limited to a more restrictive license, so adding a GPL v3 license to this repo is ok.

I'll correct the issue.
